### ISSUE TITLE
[2주차] 오브젝트 (3장 ~ 4장)

### ISSUE THREAD

**Issue by eamon3481** [mico-members/SDJ-Book-Discussion#10]

**Comment by eve712** [comment]
**3장**
- 애매하다면 단순하게 객체로 시작하고 반복적으로 책임과 협력을 정제해가면서 필요한 순간에 객체로부터 역할을 분리해내는 것이 가장 좋은 방법이다.(p.91)
- 역할이 중요한 이유는 동일한 협력을 수행하는 객체들을 추상화할 수 있기 때문이다.(p.94)

**4장**
- 접근자와 수정자 메서드는 객체 내부의 상태에 대한 어떤 정보도 캡슐화하지 못한다.
- 속성의 가시성을 private으로 설정했다고 해도 접근자와 수정자를 통해 속성을 외부로 제공하고 있다면 캡슐화를 위반하는 것이다.

**Comment by eamon3481** [comment]
3장
- 책임이란 무엇일까?
-> 객체의 책임을 크게 '하는것'과 '아는것'의 범주로 나누어 세분화 된다.

- 책임을 할당할 후보는 객체 혹은 역할일수 있고, 후보에 어떤 책임을 할당하는 것인가에 집중한다.

- 연극 안에서 배역을 연기하는 배우라는 은유는 협력 안에서 역할을 수행하는 객체라는 관점이 가진 입체적인 측면들을 훌륭하게 담아낸다.

- 일반적으로 역할은 객체가 협력에 참여하는 "잠시동안에만" 존재하는 일시적인 개념이다. 
- 오직 문맥안에서 무엇을 하는지에 의해서만 결정
- 동일한 객체라고 하더라도 객체가 참여하는협력에 따라 객체의 얼굴은 계속 바뀌게된다.

**Comment by hayoung123** [comment]
3장
역시나 객체의 핵심은 협력, 책임, 역할이다.  객체 내부구현을 캡슐화 하는 것은 중요하다. -> 객체의 변경에 대한 파급효과를 최소화 할 수 있기 때문

객체의 역할이 있기 때문에 재사용이 가능해진다. 
- 협력에 적합한 책임을 수행하는 대상이 한 종류 -> 객체
- 협력에 여러 객체들이 참여할 수 있다면 -> 역할

4장
객체지향이 강력한 이유는 캡슐화를 통해 어떤 변경의 파급효과를 최소화 할 수 있기 때문이다. 캡슐화는 불안정한 부분과 안정한 부분을 분리한다. 캡슐화란? 변경 가능성이 높은 부분을 객체 내부로 숨기는 수상화 기법
- 구현: 변경이 될 가능성이 높은 부분
- 인터페이스: 상대적으로 안정적인 부분 (인터페이스가 자주 바뀌면 힘들다.)

객제지향 설계의 무게 중심은 객체 내부가 아닌 외부 객체와 소통하는 외부이다.
