### ISSUE TITLE
[3주차] 오브젝트 (5장 ~ 6장) 

### ISSUE THREAD

**Issue by eve712** [mico-members/SDJ-Book-Discussion#11]

**Comment by eve712** [comment]
**5장**
- 객체에게 책임을 할당하는 첫 번째 원칙은 책임을 수행할 정보를 알고 있는 객체에게 책임을 할당하는 것 (정보 전문가 패턴)
- 일반적으로 설계를 개선하는 작업은 변경의 이유가 하나 이상인 클래스를 찾는 것으로부터 시작하는 것이 좋다.
    - 인스턴스 변수가 초기화되는 시점을 살펴보자. -> 함께 초기화되는 속성을 기준으로 코드 분리 
    - 메서드들이 인스턴스 변수를 사용하는 방식을 살펴보자. -> 속성 그룹과 해당 그룹에 접근하는 메서드 그룹을 기준으로 코드 분리

**Comment by hayoung123** [comment]
5장
- 변경에 따라 클래스를 분리하고 인터페이스를 이용해 변경을 캡슐화하는 것은 설계의 결합도와 응집도를 향상시킨다.
  -> 클래스가 여러 역할을 하고 있다면 다형성을 활용하든해서 분리해봐라
- 유연성은 의존성 관리의 문제다.
- 처음부터 책임주도설계로 코드를 작성하기는 힘드니 리팩토링을 하자.

6장
- 시그니처란? 오퍼레이션(메서드)의 명세를 나타낸 것 (이름과 인자를 포함) 
- 인터페이스는 객체가 어떻게 하는지가 아니라 무엇을 하는지 서술해야 한다. 
- 프로시저, 함수의 차이 : 프로시저 - 내부 상태를 변경하는 것 && 반환 값 X / 함수 - 내부상태변화X && 반환 값 O
