### ISSUE TITLE
[1주차] 협력하는 객체들의 공동체

### ISSUE THREAD

**Issue by somedaycode** [mico-members/SDJ-Book-Discussion#2]

**Comment by eve712** [comment]
### 내가 공부해야할 키워드
- implements
- 어답터패턴
- abstract class
- abstract, private

**Comment by somedaycode** [comment]
어떻게 역할과 책임을 정확히 분리할 것인가?
코드량은 많아진다.

**Comment by hayoung123** [comment]
책임과 메세지를 중점으로 고민해볼만 한 것 같다. 클래스로 Manager 같은거 만들어도 괜찮을 것 같다. 
이몬 코드 보면서 얘기하는게 아주 재밌었다

**Comment by eamon3481** [comment]
클래스의 구조와 메서드가 아니라 객체의 역할 / 책임 / 협력에 집중하라!!

**Comment by eamon3481** [comment]
클래스(자바스크립트 클래스가 아닌 일반적인)와 프로토타입의 차이가 멀까요
