### ISSUE TITLE
[2주차] 이상한 나라의 객체

### ISSUE THREAD

**Issue by somedaycode** [mico-members/SDJ-Book-Discussion#3]

**Comment by eamon3481** [comment]
읽으면서 정리한 것들
https://muddy-bobcat-991.notion.site/2-58a0ffa9ef924d8c9b58b3a45f2a1e12

**Comment by eamon3481** [comment]
상태를 먼저 결정할 경우 캡슐화가 저해된다.상태가 객체 내부로 깔끔하게  캡슐화 되지 못하고 공용 인터페이스에 그대로 노출되어버릴 확률이 높아진다 

이 이야기의 근거나 예시가 궁금하다.

**Comment by eamon3481** [comment]
```
class Alice {
	position : "통로" | "정원";
	height : number
	constructor(position, height) {
      this.position = position; 
			this.height = height
			this.cake = new Cake()
    }
	
	eatCake() {
		this.decreaseHeight()	
		this.cake.eaten(20)
	}
	
	decreaseHeight () {
	}

	passDoor () {
		if(this.height > 40){
			this.movePositionToDoor()
		}
	}
	movePositionToDoor() {
		if(this.position === "정원"){
			this.position = "통로"
			return
		}

		if(this.position === "통로"){
			this.position = "정원"
			return
		}
	}
	
}

class Cake () {
	constructor() {
      this.amount = 100; 
    }
	
	eaten (quantity) {
		   this.amount = this.amount - quantity; 
	}
	
}
```
alice 객체와 cake 객체를 만들어보았다.

**Comment by somedaycode** [comment]
> ```
> class Alice {
> 	position : "통로" | "정원";
> 	height : number
> 	constructor(position, height) {
>       this.position = position; 
> 			this.height = height
> 			this.cake = new Cake()
>     }
> 	
> 	eatCake() {
> 		this.decreaseHeight()	
> 		this.cake.eaten(20)
> 	}
> 	
> 	decreaseHeight () {
> 	}
> 
> 	passDoor () {
> 		if(this.height > 40){
> 			this.movePositionToDoor()
> 		}
> 	}
> 	movePositionToDoor() {
> 		if(this.position === "정원"){
> 			this.position = "통로"
> 			return
> 		}
> 
> 		if(this.position === "통로"){
> 			this.position = "정원"
> 			return
> 		}
> 	}
> 	
> }
> 
> class Cake () {
> 	constructor() {
>       this.amount = 100; 
>     }
> 	
> 	eaten (quantity) {
> 		   this.amount = this.amount - quantity; 
> 	}
> 	
> }
> ```
> 
> alice 객체와 cake 객체를 만들어보았다.

앨리스는 언제나 케이크를 가지게 될 텐데 이 부분을 개선할 여지가 있을까요?

**Comment by eamon3481** [comment]
@somedaycode 펍썹패턴...? 뾰족한수 있으면 알려주세요

**Comment by somedaycode** [comment]
@eamon3481 Cake를 인자로 받거나.. 앨리스에게 인벤토리라는 개념을 줘서 케이크를 담을 수 있게..?
게임캐릭터 만드는 느낌이네요 ㅋㅋ

**Comment by hongbiii** [comment]
오브젝트 책 9-3장 "의존성 주입" 에서 의존성을 해결하는 방법이 세 가지 있다고 나오네요
- 생성자 주입
- setter 주입
- 메서드 주입

만약 인벤토리라는 개념이 추가적으로 생긴다면
인벤토리 또한 클래스로 만들어야 하지 않을까 싶은데 🤔

<img width="797" alt="image" src="https://user-images.githubusercontent.com/60209518/185781082-9c1ccf64-c109-4280-8b21-6e07899f8cc1.png">

**Comment by somedaycode** [comment]
> 오브젝트 책 9-3장 "의존성 주입" 에서 의존성을 해결하는 방법이 세 가지 있다고 나오네요
> 
> * 생성자 주입
> * setter 주입
> * 메서드 주입
> 
> 만약 인벤토리라는 개념이 추가적으로 생긴다면 인벤토리 또한 클래스로 만들어야 하지 않을까 싶은데 🤔
> 
> <img alt="image" width="797" src="https://user-images.githubusercontent.com/60209518/185781082-9c1ccf64-c109-4280-8b21-6e07899f8cc1.png">

객사오 끝내고 빨리 오브젝트도 보고싶네요.
`Inventory`도 만들어서 인스턴스를 전달해줘야 고민했었는데, 메서드를 전달하는 것도 방법이였네요
