### ISSUE TITLE
[3-4주차] 타입과 추상화 - 역할, 책임, 협력

### ISSUE THREAD

**Issue by somedaycode** [mico-members/SDJ-Book-Discussion#4]
3장 : 타입과 추상화
4장 : 역할, 책임, 협력

벌써 반 정도 읽은 것 같네요!?

**Comment by somedaycode** [comment]
참고링크
- [Composite Pattern](https://refactoring.guru/design-patterns/composite)

**Comment by hayoung123** [comment]
컴포짓 패턴에 대해 배웠다. 굿

**Comment by somedaycode** [comment]
somedaycode: [블로그 정리](https://somedaycode.tistory.com/28)

**Comment by eamon3481** [comment]
역할을 doing 과 knowing 으로 나누는데 요거에 대한 코드적 예시가 있을까요?

**Comment by hongbiii** [comment]
컴포짓 패턴이 뭐예여?
