### ISSUE TITLE
[5주차] 책임과 메시지

### ISSUE THREAD

**Issue by somedaycode** [mico-members/SDJ-Book-Discussion#5]
각자 이번주 내용에 대한 질문 몇가지를 준비하여 서로 답하는 시간을 가져보자 - from @eamon3481 
- 이슈 댓글

스터디를 더 효율적으로 진행할 수 있는 방법에 대해 고민도 해봅시다.

**Comment by somedaycode** [comment]
블로그정리 : https://somedaycode.tistory.com/30

**Comment by eamon3481** [comment]
정리 : https://muddy-bobcat-991.notion.site/5-f3d2df26886a407db98ab4ebe44cb1bc
