### ISSUE TITLE
[6주차] 객체 지도

### ISSUE THREAD

**Issue by eamon3481** [mico-members/SDJ-Book-Discussion#6]

**Comment by eamon3481** [comment]
유스 케이스의 특성 
단순한 피처와는 다르다. 
→ 중도 해지 이자액을 계산한다라는 유스케이스에 “정기 예금 정보를 보여준다" 가 들어가는가?

**Comment by eamon3481** [comment]
도메인 모델에서는 상태를 협력에서는 메서드들 
유스케이스에서는 책임을 결정하는 것일까?

책에서 이자율과 이자 모델을 나눈 근거는 무엇일까?

**Comment by eamon3481** [comment]
노션 정리 : https://muddy-bobcat-991.notion.site/6-51b63b5acd124a26b7ef7c871da3d582

**Comment by somedaycode** [comment]
다음 주 도메인 모델 및 유즈케이스 작성해보고 추후 프로젝트 같이 작성해보기

**Comment by eve712** [comment]
다음 내용들이 이해가 잘 안 되네요.
> (p.202 세 번째 문단)
> 유스케이스에서 출발해 객체들의 협력으로 이어지는 일련의 흐름은 객체 안에 다른 객체를 포함하는 재귀적 합성이라는 객체지향의 기본 개념을 잘 보여준다. 
> ... 
> 객체에 대한 재귀는 객체지향의 개념을 모든 추상화 수준에서 적용 가능하게 하는 동시에 객체지향 패러다임을 어떤 곳에서든 일관성 있게 적용할 수 있게 한다.

> (p.202 스몰토크의 설계) 녹색 박스 전체 이해 안 됨

**Comment by eve712** [comment]
오늘 카일의 질문 중 '다형성은 상속으로 구현하는 것인가?'
> (p.204 예제 가장 밑에 있는 문장)
> 인터페이스를 정의하는 추상 클래스와 인터페이스를 구현하는 구체적인 클래스 간의 상속 관계는 클래스 기반의 객체지향 언어에서 다형성을 구현하는 가장 기본적인 방법이다.
