### ISSUE TITLE
[1주차] 오브젝트 (1장 ~ 2장)

### ISSUE THREAD

**Issue by somedaycode** [mico-members/SDJ-Book-Discussion#9]

**Comment by hayoung123** [comment]
1장 - 의존성을 줄이면서 코드의 변화를 보는 재미가 있었던 장. 변화에 유연한 코드를 위해서는 의존성을 줄이는 것이 중요하다.

**Comment by hayoung123** [comment]
2장 - 책임있는 객체는 협력에 참여한다. 등등 토끼책의 기본내용 반복 
상속도 문제가 있다. - 캡슐화 위반 (부모의 내부구조를 알아야 되고, 부모 클래스 구현이 자식에 노출 => 부모 클래스 구현 변경 시 위험에 노출 될 수 있음) => 합성으로 해결하는 방법도 있더라

**Comment by eve712** [comment]
**1장**
설계는 트레이드오프의 산물이다. 어떤 경우에도 모든 사람들을 만족시킬 수 있는 설계를 만들 수는 없다.

**Comment by somedaycode** [comment]
1. 설계를 어렵게 만드는 것은 의존성이다.

2. 코드 설계, 리팩토링 과정에서 언제나 트레이드 오프는 있다.

**Comment by eamon3481** [comment]
2장 
메시지와 메서드를 구분하는 것은 중요하다. 이 구분에서 부터 다형성의 개념을 출발한다.

지금 까지는 Screening 이 Movie 의 calculateMovieFee 메서드를 호출한다 라고 말했지만 사실은 Screening 이 Movie 에게 calculateMovieFee 라는 메세지를 전송한다.

메세지를 수신한 Movie 는 스스로 적절한 메서드를 선택한다. 루비 같은 동적 타입언어에서는 다른 시그니처를 가진 메서드를 통해서도 해당 메시지에 응답할 수 있다.

이 부분에서 객사오에서 설명한 메세지와 메서드의 차이점을 좀 더 깊게 이해하게 되었다
